name: Release Preparation

on:
  push:
    branches:    
      - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEST_BRANCH: ${{ github.ref }}
    steps:
    - name: log
      run: echo '${{ toJSON(github) }}'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout manifest repo
      uses: ./
      with:
        name: 'application.yaml'
        srcRevision: 'develop'
        destRevision: ${{ env.DEST_BRANCH }}
