name: Release Preparation

on:
  push:
    branches:    
      - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: $ {{ github.repository_owner }}
      DEST_BRANCH: ${{ github.ref }}
    steps:
    - name: log
      run: echo '${{ toJSON(github) }}'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Change targetRevision
      uses: ./
      with:
        name: 'application.yaml'
        repository: ${{ env.OWNER }}
        srcRevision: 'feature/init'
        destRevision: ${{ env.DEST_BRANCH }}
